[package]
name = "daft"
version = "0.1.0"
readme = "./README.md"
license = "Apache-2.0"

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "0.1.4"
spin = "0.3.4"

[dependencies.multiboot2]
git = "https://github.com/phil-opp/multiboot2-elf64"
